
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
  client:
    build: ./client
    environment:
      - VITE_API_URL=http://server:8080
    ports:
      - "5173:80"
    depends_on:
      - server
